class_name Chapter3Data
extends RefCounted

## 章节三 · 典礼上的选择 剧本数据。
##
## source 字段对应 0829全剧本V2_美术音效需求新.docx 的段落行号，
## 场景编号按剧本标注沿用：
##   场景图5 - 卧室（沿用）
##   场景图9 - 正式婚礼现场（与场景图2彩排场景区分的新占位）
##   场景图8 - 婚礼会场外静谧走廊
##   场景图10 - 结局A典礼红毯
##   场景图11 - 结局B/C酒店外阳光（占位）

const SCENE_BEDROOM := "场景图5-卧室"
const SCENE_WEDDING_HALL := "场景图9-正式婚礼现场"
const SCENE_CORRIDOR := "场景图8-婚礼会场外静谧走廊"
const SCENE_ENDING_A := "场景图10-典礼红毯"
const SCENE_ENDING_BC := "场景图11-酒店外阳光"
const SCENE_WINDOW_TALK := "小凌思羽窗边谈话"
const SCENE_ENDING_A_VEIL := "结局A-带头纱的婚礼现场"
const SCENE_ENDING_A_NO_VEIL := "结局A-不带头纱结婚照"
const SCENE_ENDING_B_RUN_CARPET := "结局B-光腿在地毯上奔跑"
const SCENE_ENDING_BC_SUN_RUN := "结局BC-阳光下奔跑"
const SCENE_WINDOW_TALK_2 := "小凌思羽窗边谈话-2"
const SCENE_ENDING_B_RUN_CARPET_1 := "结局B-光腿在地毯上奔跑-1"
const SCENE_ENDING_C_LEAVE := "结局C-女主离开思羽看着她"

static func build_events() -> Array[Dictionary]:
	var events: Array[Dictionary] = []
	events.append_array(_main_events())
	events.append_array(_ending_a_events())
	events.append_array(_ending_b_events())
	events.append_array(_ending_c_events())
	return events


static func _main_events() -> Array[Dictionary]:
	return [
		{"type": "video", "source": 923, "video": "res://assets/videos/opening_video.ogv", "poster": "res://assets/backgrounds/场景转换后的妈妈.png", "name": "卧室视频", "label": "卧室", "subtitle": "开场视频 · 定格尾帧"},
		{"type": "audio", "source": 916, "action": "start", "stream": "chapter3_bgm_reality_return", "status": "现实回归同一房间不同的人 BGM 起"},
		{"type": "scene", "source": 923, "name": "场景转换后的妈妈", "label": "场景转换后的妈妈", "subtitle": "场景转换后的妈妈"},
		{"type": "line", "source": 916, "speaker": "旁白", "text": "妈妈的声音从很远的地方传来。"},
		{"type": "line", "source": 917, "speaker": "妈妈", "text": "小凌。"},
		{"type": "line", "source": 918, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 919, "speaker": "妈妈", "text": "小凌。"},
		{"type": "line", "source": 920, "speaker": "旁白", "text": "声音越来越近。"},

		{"type": "line", "source": 924, "speaker": "妈妈", "text": "小凌，醒醒。"},
		{"type": "line", "source": 925, "speaker": "旁白", "text": "妈妈的一只戴着戒指的手伸过来，一把把小凌拽起来。", "status": "妈妈的一只戴着戒指的手伸过来，一把把小凌拽起来。"},
		{"type": "effect", "source": 926, "id": "flash", "status": "画面突然亮起。"},
		{"type": "line", "source": 927, "speaker": "旁白", "text": "小凌猛地睁开眼。", "status": "小凌猛地睁开眼。"},
		{"type": "line", "source": 928, "speaker": "旁白", "text": "眼前不是湖，也不是森林。"},
		{"type": "line", "source": 929, "speaker": "旁白", "text": "是自己的卧室。"},
		{"type": "line", "source": 930, "speaker": "妈妈", "text": "化妆师已经到了。"},
		{"type": "line", "source": 931, "speaker": "小凌", "text": "……"},

		{"type": "scene", "source": 933, "name": "正式婚礼现场", "label": "正式婚礼现场", "subtitle": "image#1 · 正式婚礼现场"},
		{"type": "audio", "source": 932, "action": "stop", "stream": "chapter3_bgm_reality_return", "status": "现实回归 BGM 淡出"},
		{"type": "audio", "source": 932, "action": "start", "stream": "chapter3_bgm_door_wedding", "status": "隔门婚礼主题远去 BGM 起"},
		{"type": "line", "source": 934, "speaker": "旁白", "text": "酒店会场人来人往。"},
		{"type": "line", "source": 936, "speaker": "旁白", "text": "鲜花。气球。礼服。香槟。来宾。"},
		{"type": "line", "source": 937, "speaker": "旁白", "text": "所有人都在笑。所有人都在说“恭喜”。"},
		{"type": "line", "source": 938, "speaker": "旁白", "text": "小凌跟着妈妈往前走。"},
		{"type": "line", "source": 939, "speaker": "妈妈", "text": "一会儿你先去休息室准备，等主持人叫你，我先去他爸妈那边了。"},
		{"type": "line", "source": 940, "speaker": "小凌", "text": "嗯。"},
		{"type": "line", "source": 941, "speaker": "妈妈", "text": "思雨已经到了。"},
		{"type": "line", "source": 942, "speaker": "旁白", "text": "小凌停了一下。", "status": "小凌停了一下。"},
		{"type": "line", "source": 943, "speaker": "旁白", "text": "她看向会场门外的走廊。"},
		{"type": "scene", "source": 944, "name": "静谧走廊", "label": "静谧走廊", "subtitle": "image#2 · 静谧走廊"},

		{"type": "line", "source": 947, "speaker": "旁白", "text": "走廊尽头有一道很长的光，光下面站着一个人。是思雨。"},
		{"type": "line", "source": 947, "speaker": "旁白", "text": "走廊尽头有一道很长的光，光下面站着一个人。是思雨。"},
		{"type": "line", "source": 948, "speaker": "旁白", "text": "他正低头看手机。"},
		{"type": "line", "source": 949, "speaker": "旁白", "text": "周围的人不断经过。"},
		{"type": "line", "source": 950, "speaker": "旁白", "text": "他却没有注意到小凌。"},
		{"type": "line", "source": 951, "speaker": "旁白", "text": "小凌看了他很久。"},
		{"type": "line", "source": 952, "speaker": "旁白", "text": "然后朝他走过去。"},
		{"type": "line", "source": 956, "speaker": "旁白", "text": "走廊里很安静。"},
		{"type": "line", "source": 957, "speaker": "旁白", "text": "思雨终于抬起头。"},

		{"type": "line", "source": 958, "speaker": "思雨", "text": "你怎么出来了？"},
		{"type": "line", "source": 959, "speaker": "小凌", "text": "我想跟你聊聊。"},
		{"type": "line", "source": 960, "speaker": "旁白", "text": "思雨看了一眼时间。", "status": "思雨看了一眼时间。"},
		{"type": "line", "source": 961, "speaker": "思雨", "text": "现在？"},
		{"type": "scene", "source": 962, "name": "小凌思羽窗边谈话", "label": "小凌思羽窗边谈话", "subtitle": "image#3 · 小凌思羽窗边谈话"},
		{"type": "line", "source": 962, "speaker": "小凌", "text": "嗯。"},
		{"type": "line", "source": 963, "speaker": "思雨", "text": "马上要开始了。"},
		{"type": "line", "source": 964, "speaker": "小凌", "text": "我知道。"},
		{"type": "line", "source": 965, "speaker": "旁白", "text": "思雨看着她。", "status": "思雨看着她。"},
		{"type": "line", "source": 966, "speaker": "旁白", "text": "发现她的表情和平时不太一样。"},
		{"type": "line", "source": 967, "speaker": "思雨", "text": "怎么了？"},
		{"type": "line", "source": 968, "speaker": "旁白", "text": "小凌没有马上回答。", "status": "小凌没有马上回答。"},
		{"type": "line", "source": 969, "speaker": "旁白", "text": "她低头看着自己的婚纱。"},

		{"type": "line", "source": 970, "speaker": "小凌", "text": "你喜欢我吗？"},
		{"type": "line", "source": 971, "speaker": "旁白", "text": "思雨愣了一下。", "status": "思雨愣了一下。"},
		{"type": "line", "source": 972, "speaker": "思雨", "text": "当然。"},
		{"type": "line", "source": 973, "speaker": "小凌", "text": "为什么？"},
		{"type": "line", "source": 974, "speaker": "思雨", "text": "因为是你啊。"},
		{"type": "line", "source": 975, "speaker": "小凌", "text": "那你知道我喜欢什么吗？"},
		{"type": "line", "source": 976, "speaker": "旁白", "text": "思雨没有说话。"},
		{"type": "line", "source": 977, "speaker": "小凌", "text": "我喜欢什么电影。"},
		{"type": "line", "source": 978, "speaker": "小凌", "text": "喜欢什么书。"},
		{"type": "line", "source": 979, "speaker": "小凌", "text": "以后想去哪儿。"},
		{"type": "line", "source": 980, "speaker": "小凌", "text": "想做什么工作。"},
		{"type": "line", "source": 981, "speaker": "小凌", "text": "甚至……"},
		{"type": "line", "source": 982, "speaker": "旁白", "text": "她停了一下。", "status": "她停了一下。"},
		{"type": "line", "source": 983, "speaker": "小凌", "text": "我到底想不想结婚。"},
		{"type": "line", "source": 984, "speaker": "旁白", "text": "思雨皱了皱眉。", "status": "思雨皱了皱眉。"},
		{"type": "line", "source": 985, "speaker": "思雨", "text": "你到底怎么了？"},
		{"type": "line", "source": 986, "speaker": "小凌", "text": "我不知道。"},
		{"type": "line", "source": 987, "speaker": "思雨", "text": "又是“不知道”。"},
		{"type": "line", "source": 988, "speaker": "旁白", "text": "小凌抬起头。", "status": "小凌抬起头。"},
		{"type": "line", "source": 989, "speaker": "旁白", "text": "这一次，她没有躲开。"},
		{"type": "line", "source": 990, "speaker": "小凌", "text": "对。"},
		{"type": "line", "source": 991, "speaker": "小凌", "text": "我就是不知道。"},
		{"type": "line", "source": 992, "speaker": "小凌", "text": "我不知道自己是不是一个合格的大人。"},
		{"type": "line", "source": 993, "speaker": "小凌", "text": "不知道别人到了我这个年纪，是不是都应该知道自己要什么。"},
		{"type": "line", "source": 994, "speaker": "小凌", "text": "不知道我是不是应该辞掉现在的工作。"},
		{"type": "line", "source": 995, "speaker": "小凌", "text": "不知道结婚以后，我是不是会变成一个我自己都不认识的人。"},
		{"type": "line", "source": 996, "speaker": "旁白", "text": "思雨沉默。"},
		{"type": "line", "source": 997, "speaker": "旁白", "text": "小凌的声音开始发抖。"},
		{"type": "line", "source": 998, "speaker": "小凌", "text": "我昨天一直在想……"},
		{"type": "line", "source": 999, "speaker": "小凌", "text": "如果我今天真的跟你走进去了。"},
		{"type": "line", "source": 1000, "speaker": "小凌", "text": "以后是不是就只能这样了。"},
		{"type": "line", "source": 1001, "speaker": "思雨", "text": "什么叫“只能这样”？"},
		{"type": "line", "source": 1002, "speaker": "小凌", "text": "就是……"},
		{"type": "line", "source": 1003, "speaker": "旁白", "text": "小凌想了很久。", "status": "小凌想了很久。"},
		{"type": "line", "source": 1004, "speaker": "小凌", "text": "每天上班。"},
		{"type": "line", "source": 1005, "speaker": "小凌", "text": "回家。"},
		{"type": "line", "source": 1006, "speaker": "小凌", "text": "吃饭。"},
		{"type": "line", "source": 1007, "speaker": "小凌", "text": "睡觉。"},
		{"type": "line", "source": 1008, "speaker": "小凌", "text": "然后有一天发现，好像已经过了十年。"},
		{"type": "line", "source": 1009, "speaker": "小凌", "text": "我不知道自己什么时候变成了这样。"},
		{"type": "line", "source": 1010, "speaker": "思雨", "text": "可是这些不都是生活吗？"},
		{"type": "line", "source": 1011, "speaker": "小凌", "text": "我知道。"},
		{"type": "line", "source": 1012, "speaker": "小凌", "text": "所以我才害怕。"},
		{"type": "line", "source": 1013, "speaker": "旁白", "text": "思雨看着她。", "status": "思雨看着她。"},
		{"type": "line", "source": 1014, "speaker": "思雨", "text": "你是不是觉得我耽误你了？"},
		{"type": "line", "source": 1015, "speaker": "旁白", "text": "小凌摇头。", "status": "小凌摇头。"},
		{"type": "line", "source": 1016, "speaker": "小凌", "text": "不是。"},
		{"type": "line", "source": 1017, "speaker": "小凌", "text": "你没有做错什么。"},
		{"type": "line", "source": 1018, "speaker": "小凌", "text": "你很好。"},
		{"type": "line", "source": 1019, "speaker": "思雨", "text": "那为什么？"},
		{"type": "line", "source": 1020, "speaker": "旁白", "text": "小凌看着他。", "status": "小凌看着他。"},
		{"type": "line", "source": 1021, "speaker": "小凌", "text": "因为我跟不上你。"},
		{"type": "line", "source": 1022, "speaker": "旁白", "text": "思雨愣住。", "status": "思雨愣住。"},
		{"type": "line", "source": 1023, "speaker": "小凌", "text": "你知道自己要什么。"},
		{"type": "line", "source": 1024, "speaker": "小凌", "text": "你知道什么时候该工作，什么时候该买房，什么时候该结婚。"},
		{"type": "line", "source": 1025, "speaker": "小凌", "text": "你甚至知道今天几点化妆，几点拍照，几点交换戒指。"},
		{"type": "line", "source": 1026, "speaker": "小凌", "text": "可是我不知道。"},
		{"type": "line", "source": 1027, "speaker": "思雨", "text": "那你可以慢慢知道。"},
		{"type": "line", "source": 1028, "speaker": "小凌", "text": "可是你已经在往你的路上走了。"},
		{"type": "line", "source": 1029, "speaker": "小凌", "text": "我一直在追你。"},
		{"type": "line", "source": 1030, "speaker": "小凌", "text": "追着追着，我突然不知道……"},
		{"type": "line", "source": 1031, "speaker": "小凌", "text": "我是不是还在走自己的路。"},
		{"type": "line", "source": 1032, "speaker": "旁白", "text": "走廊安静下来。"},
		{"type": "line", "source": 1033, "speaker": "旁白", "text": "远处传来主持人的声音。"},
		{"type": "line", "source": 1034, "speaker": "旁白", "text": "“各位来宾，请稍作准备……婚礼即将开始。”"},
		{"type": "line", "source": 1035, "speaker": "旁白", "text": "思雨往前走了一步。", "status": "思雨往前走了一步。"},
		{"type": "line", "source": 1036, "speaker": "思雨", "text": "小凌。"},
		{"type": "line", "source": 1037, "speaker": "旁白", "text": "小凌抬头。", "status": "小凌抬头。"},
		{"type": "line", "source": 1038, "speaker": "思雨", "text": "我可以等你。"},
		{"type": "line", "source": 1039, "speaker": "旁白", "text": "小凌没有说话。", "status": "小凌没有说话。"},
		{"type": "line", "source": 1040, "speaker": "思雨", "text": "你不需要今天想清楚所有的事。"},
		{"type": "line", "source": 1041, "speaker": "小凌", "text": "那婚礼呢？"},
		{"type": "line", "source": 1042, "speaker": "旁白", "text": "思雨沉默。"},
		{"type": "line", "source": 1043, "speaker": "思雨", "text": "婚礼可以继续。"},
		{"type": "line", "source": 1044, "speaker": "小凌", "text": "如果我现在说，我不想呢？"},
		{"type": "line", "source": 1045, "speaker": "旁白", "text": "思雨看着她。", "status": "思雨看着她。"},
		{"type": "line", "source": 1046, "speaker": "思雨", "text": "那……"},
		{"type": "line", "source": 1047, "speaker": "旁白", "text": "他停了很久。", "status": "他停了很久。"},
		{"type": "line", "source": 1048, "speaker": "思雨", "text": "我们也可以不结。"},
		{"type": "line", "source": 1049, "speaker": "旁白", "text": "小凌第一次从他的眼睛里看到了一点慌乱。"},
		{"type": "line", "source": 1050, "speaker": "思雨", "text": "但是你能不能别就这样走。"},
		{"type": "line", "source": 1051, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 1052, "speaker": "思雨", "text": "我们在一起这么久。"},
		{"type": "line", "source": 1053, "speaker": "思雨", "text": "我不想因为你今天害怕，就把我们全部都丢掉。"},
		{"type": "line", "source": 1054, "speaker": "旁白", "text": "她看着思雨。", "status": "她看着思雨。"},
		{"type": "line", "source": 1055, "speaker": "小凌", "text": "我不是害怕结婚。"},
		{"type": "line", "source": 1056, "speaker": "思雨", "text": "那是什么？"},
		{"type": "line", "source": 1057, "speaker": "小凌", "text": "我害怕……"},
		{"type": "line", "source": 1058, "speaker": "旁白", "text": "她停了一下。", "status": "她停了一下。"},
		{"type": "line", "source": 1059, "speaker": "小凌", "text": "我明明不确定，却还是因为所有人都觉得我应该结婚，所以就结了。"},
		{"type": "line", "source": 1060, "speaker": "旁白", "text": "思雨没有说话。"},
		{"type": "line", "source": 1061, "speaker": "小凌", "text": "我不想这样。"},
		{"type": "line", "source": 1062, "speaker": "旁白", "text": "远处再次传来主持人的声音：“新娘准备。”"},
		{"type": "line", "source": 1063, "speaker": "旁白", "text": "工作人员的脚步声越来越近。"},
		{"type": "line", "source": 1064, "speaker": "工作人员", "text": "思雨、小凌，马上到时间了。"},
		{"type": "line", "source": 1065, "speaker": "旁白", "text": "小凌没有回答。", "status": "小凌没有回答。"},
		{"type": "line", "source": 1066, "speaker": "旁白", "text": "工作人员看向思雨。", "status": "工作人员看向思雨。"},
		{"type": "line", "source": 1067, "speaker": "旁白", "text": "思雨摆了摆手。", "status": "思雨摆了摆手。"},
		{"type": "line", "source": 1068, "speaker": "旁白", "text": "工作人员离开。", "status": "工作人员离开。"},
		{"type": "line", "source": 1069, "speaker": "旁白", "text": "走廊再次安静。"},
		{"type": "line", "source": 1070, "speaker": "思雨", "text": "那你想怎么办？"},

		{"type": "effect", "source": 1073, "id": "screen_dim", "level": 0.55, "duration": 0.8, "status": "屏幕逐渐暗下来。"},
		{"type": "choice", "source": 1074, "prompt": "小凌最后的选择是……", "options": [
			{"id": "A", "text": "A：走进婚礼", "jump_to": "ending_a"},
			{"id": "B", "text": "B：取消婚礼", "jump_to": "ending_b"},
			{"id": "C", "text": "C：暂缓婚礼", "jump_to": "ending_c"},
		]},
	]


static func _ending_a_events() -> Array[Dictionary]:
	return [
		{"type": "label", "id": "ending_a"},
		{"type": "audio", "source": 1076, "action": "stop", "stream": "chapter3_bgm_door_wedding", "status": "隔门婚礼主题远去 BGM 淡出"},
		{"type": "audio", "source": 1076, "action": "start", "stream": "ending_bgm_a", "status": "结局A 两主题主动融合 BGM 起"},
		{"type": "scene", "source": 1076, "name": "小凌思羽窗边谈话-1", "label": "结局A", "subtitle": "image#4 · 小凌思羽窗边谈话-1"},
		{"type": "effect", "source": 1077, "id": "screen_bright", "level": 0.0, "duration": 0.6, "status": ""},
		{"type": "line", "source": 1077, "speaker": "旁白", "text": "小凌看着思雨。", "status": "小凌看着思雨。"},
		{"type": "line", "source": 1078, "speaker": "小凌", "text": "我还是想试试。"},
		{"type": "line", "source": 1079, "speaker": "旁白", "text": "思雨明显松了一口气。", "status": "思雨明显松了一口气。"},
		{"type": "line", "source": 1080, "speaker": "小凌", "text": "但是有一件事情你要答应我。"},
		{"type": "line", "source": 1081, "speaker": "思雨", "text": "什么？"},
		{"type": "line", "source": 1082, "speaker": "小凌", "text": "以后如果我想做别的事情。"},
		{"type": "line", "source": 1083, "speaker": "小凌", "text": "如果我想辞职。"},
		{"type": "line", "source": 1084, "speaker": "小凌", "text": "想一个人去旅行。"},
		{"type": "line", "source": 1085, "speaker": "小凌", "text": "想学一个新的东西。"},
		{"type": "line", "source": 1086, "speaker": "小凌", "text": "甚至有一天……"},
		{"type": "line", "source": 1087, "speaker": "小凌", "text": "我发现自己不想过现在这样的生活了。"},
		{"type": "line", "source": 1088, "speaker": "小凌", "text": "你不要告诉我，这是不成熟。"},
		{"type": "line", "source": 1089, "speaker": "旁白", "text": "思雨看着她。", "status": "思雨看着她。"},
		{"type": "line", "source": 1090, "speaker": "旁白", "text": "过了一会儿。", "status": "过了一会儿。"},
		{"type": "line", "source": 1091, "speaker": "思雨", "text": "好。"},
		{"type": "line", "source": 1092, "speaker": "小凌", "text": "你真的答应？"},
		{"type": "line", "source": 1093, "speaker": "思雨", "text": "我答应。"},
		{"type": "line", "source": 1094, "speaker": "旁白", "text": "小凌看了他很久。", "status": "小凌看了他很久。"},
		{"type": "line", "source": 1095, "speaker": "旁白", "text": "然后伸出手。"},
		{"type": "line", "source": 1096, "speaker": "旁白", "text": "思雨握住她。"},
		{"type": "line", "source": 1098, "speaker": "旁白", "text": "两个人一起走向典礼厅。"},
		{"type": "line", "source": 1099, "speaker": "旁白", "text": "门缓缓打开。"},
		{"type": "scene", "source": 1100, "name": SCENE_ENDING_A_VEIL, "label": "结局A-带头纱的婚礼现场", "subtitle": "结局A-带头纱的婚礼现场"},
		{"type": "line", "source": 1100, "speaker": "旁白", "text": "婚礼进行曲再次响起。"},
		{"type": "line", "source": 1101, "speaker": "旁白", "text": "小凌走上红毯。"},
		{"type": "line", "source": 1102, "speaker": "旁白", "text": "这一次，她自己掀开头纱。"},
		{"type": "line", "source": 1104, "speaker": "旁白", "text": "前方是思雨。"},
		{"type": "line", "source": 1105, "speaker": "旁白", "text": "灯光亮起。"},
		{"type": "line", "source": 1106, "speaker": "旁白", "text": "小凌一步一步走过去。"},
		{"type": "scene", "source": 1107, "name": SCENE_ENDING_A_NO_VEIL, "label": "结局A-不带头纱结婚照", "subtitle": "结局A-不带头纱结婚照"},
		{"type": "line", "source": 1107, "speaker": "旁白", "text": "画面定格。", "status": "画面定格。"},
		{"type": "ending", "source": 1107, "ending_id": "A", "text": "结局 A | 走进婚礼"},
	]


static func _ending_b_events() -> Array[Dictionary]:
	return [
		{"type": "label", "id": "ending_b"},
		{"type": "audio", "source": 1110, "action": "stop", "stream": "chapter3_bgm_door_wedding", "status": "隔门婚礼主题远去 BGM 淡出"},
		{"type": "audio", "source": 1110, "action": "start", "stream": "ending_bgm_b", "status": "结局B 湖边共感被理解后的力量 BGM 起"},
		{"type": "scene", "source": 1110, "name": SCENE_WINDOW_TALK, "label": "结局B-小凌思羽窗边谈话", "subtitle": "结局B-小凌思羽窗边谈话"},
		{"type": "effect", "source": 1112, "source_dup": 1112, "id": "screen_bright", "level": 0.0, "duration": 0.6, "status": ""},
		{"type": "line", "source": 1112, "speaker": "旁白", "text": "小凌摇了摇头。", "status": "小凌摇了摇头。"},
		{"type": "line", "source": 1113, "speaker": "小凌", "text": "对不起。"},
		{"type": "line", "source": 1114, "speaker": "旁白", "text": "思雨没有说话。"},
		{"type": "line", "source": 1115, "speaker": "小凌", "text": "我还是不能进去。"},
		{"type": "line", "source": 1116, "speaker": "思雨", "text": "你想清楚了吗？"},
		{"type": "line", "source": 1117, "speaker": "小凌", "text": "嗯。"},
		{"type": "line", "source": 1118, "speaker": "旁白", "text": "思雨愣了一下，低下头。", "status": "思雨愣了一下，低下头。"},
		{"type": "line", "source": 1119, "speaker": "旁白", "text": "很久以后，他轻轻点了点头。", "status": "很久以后，他轻轻点了点头。"},
		{"type": "line", "source": 1120, "speaker": "思雨", "text": "好。"},
		{"type": "scene", "source": 1123, "name": SCENE_ENDING_B_RUN_CARPET, "label": "结局B-光腿在地毯上奔跑", "subtitle": "结局B-光腿在地毯上奔跑"},
		{"type": "line", "source": 1123, "speaker": "旁白", "text": "小凌转身。", "status": "小凌转身。"},
		{"type": "line", "source": 1124, "speaker": "旁白", "text": "身后的典礼厅依旧灯火通明。"},
		{"type": "line", "source": 1125, "speaker": "旁白", "text": "里面的人还在等待。"},
		{"type": "line", "source": 1126, "speaker": "旁白", "text": "小凌却第一次没有继续往前走。"},
		{"type": "line", "source": 1127, "speaker": "旁白", "text": "她转身走向酒店的出口。"},
		{"type": "line", "source": 1128, "speaker": "旁白", "text": "脱下高跟鞋，拎在手里。赤脚踩在酒店冰凉的地面上。", "status": "脱下高跟鞋，拎在手里。赤脚踩在酒店冰凉的地面上。"},
		{"type": "line", "source": 1129, "speaker": "旁白", "text": "她走着走着，跑了起来。"},
		{"type": "line", "source": 1130, "speaker": "旁白", "text": "她跑出酒店。"},
		{"type": "scene", "source": 1131, "name": SCENE_ENDING_BC_SUN_RUN, "label": "结局BC-阳光下奔跑", "subtitle": "结局BC-阳光下奔跑"},
		{"type": "line", "source": 1131, "speaker": "旁白", "text": "阳光照在脸上。小凌眯起眼睛看向太阳。"},
		{"type": "ending", "source": 1131, "ending_id": "B", "text": "结局 B | 取消婚礼"},
	]


static func _ending_c_events() -> Array[Dictionary]:
	return [
		{"type": "label", "id": "ending_c"},
		{"type": "audio", "source": 1134, "action": "stop", "stream": "chapter3_bgm_door_wedding", "status": "隔门婚礼主题远去 BGM 淡出"},
		{"type": "audio", "source": 1134, "action": "start", "stream": "ending_bgm_c", "status": "结局C 允许不知道悬置 BGM 起"},
		{"type": "scene", "source": 1134, "name": SCENE_WINDOW_TALK_2, "label": "结局C-小凌思羽窗边谈话-2", "subtitle": "结局C-小凌思羽窗边谈话-2"},
		{"type": "effect", "source": 1135, "id": "screen_bright", "level": 0.0, "duration": 0.6, "status": ""},
		{"type": "line", "source": 1135, "speaker": "旁白", "text": "小凌看着思雨。", "status": "小凌看着思雨。"},
		{"type": "line", "source": 1136, "speaker": "小凌", "text": "我不知道。"},
		{"type": "line", "source": 1137, "speaker": "旁白", "text": "思雨没有说话。"},
		{"type": "line", "source": 1138, "speaker": "小凌", "text": "我现在真的不知道我要不要跟你结婚。"},
		{"type": "line", "source": 1139, "speaker": "小凌", "text": "但我也不知道我是不是想离开你。"},
		{"type": "line", "source": 1140, "speaker": "旁白", "text": "思雨看着她。", "status": "思雨看着她。"},
		{"type": "line", "source": 1141, "speaker": "小凌", "text": "但是我第一次觉得……"},
		{"type": "line", "source": 1142, "speaker": "小凌", "text": "不知道，也可以是一个答案。"},
		{"type": "line", "source": 1143, "speaker": "小凌", "text": "所以……"},
		{"type": "line", "source": 1144, "speaker": "小凌", "text": "我们能不能先不要决定？"},
		{"type": "line", "source": 1145, "speaker": "思雨", "text": "今天？"},
		{"type": "line", "source": 1146, "speaker": "旁白", "text": "小凌点头。", "status": "小凌点头。"},
		{"type": "line", "source": 1147, "speaker": "小凌", "text": "今天。"},
		{"type": "line", "source": 1148, "speaker": "旁白", "text": "思雨沉默很久。", "status": "思雨沉默很久。"},
		{"type": "line", "source": 1149, "speaker": "旁白", "text": "最后，他轻轻叹了一口气。", "status": "最后，他轻轻叹了一口气。"},
		{"type": "line", "source": 1150, "speaker": "思雨", "text": "好。"},
		{"type": "line", "source": 1151, "speaker": "旁白", "text": "小凌看着他。", "status": "小凌看着他。"},
		{"type": "line", "source": 1152, "speaker": "思雨", "text": "那今天就不结。"},
		{"type": "line", "source": 1153, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 1154, "speaker": "思雨", "text": "等你想好了，我们再说。"},
		{"type": "line", "source": 1157, "speaker": "旁白", "text": "小凌眼眶微微发红。", "status": "小凌眼眶微微发红。"},
		{"type": "line", "source": 1158, "speaker": "小凌", "text": "谢谢。"},
		{"type": "line", "source": 1159, "speaker": "旁白", "text": "两个人站在走廊里。"},
		{"type": "line", "source": 1160, "speaker": "旁白", "text": "典礼厅里的婚礼进行曲还在播放。"},
		{"type": "line", "source": 1161, "speaker": "旁白", "text": "工作人员从远处跑来，又停住。"},
		{"type": "line", "source": 1162, "speaker": "旁白", "text": "所有人都不知道接下来该怎么办。"},
		{"type": "line", "source": 1163, "speaker": "旁白", "text": "小凌却第一次没有觉得自己必须马上给出答案。"},
		{"type": "scene", "source": 1164, "name": SCENE_ENDING_B_RUN_CARPET_1, "label": "结局C-光腿在地毯上奔跑-1", "subtitle": "结局C-光腿在地毯上奔跑-1"},
		{"type": "line", "source": 1164, "speaker": "旁白", "text": "她转身走向酒店的出口。"},
		{"type": "line", "source": 1165, "speaker": "旁白", "text": "脱下高跟鞋，拎在手里。赤脚踩在酒店冰凉的地面上。", "status": "脱下高跟鞋，拎在手里。赤脚踩在酒店冰凉的地面上。"},
		{"type": "line", "source": 1166, "speaker": "旁白", "text": "她走着走着，跑了起来。"},
		{"type": "line", "source": 1167, "speaker": "旁白", "text": "她跑出酒店。"},
		{"type": "scene", "source": 1168, "name": SCENE_ENDING_C_LEAVE, "label": "结局C-女主离开思羽看着她", "subtitle": "结局C-女主离开思羽看着她"},
		{"type": "line", "source": 1168, "speaker": "旁白", "text": "阳光照在脸上。小凌眯起眼睛看向太阳。"},
		{"type": "ending", "source": 1168, "ending_id": "C", "text": "结局 C | 暂缓婚礼"},
	]
