extends RefCounted
class_name MysticNightData

## 《奇妙夜-世界》事件表。
##
## source 使用灰盒开发稿的段落序号并供 F4 回溯；art_scene_index 对应本次
## “奇妙夜（森林前美术素材）”交付的 1–12 号场景。动作提示按修改文档要求进入对白框。


static func build_events() -> Array[Dictionary]:
	return [
		{"type": "scene", "source": 1, "name": "奇妙夜"},
		{"type": "cg", "source": 16, "art_scene_index": 1, "name": "奇妙夜场景1", "asset": "res://assets/cutscenes/mystic_night/01_meadow.png"},
		{"type": "camera", "source": 18, "id": "shot_01_wake", "status": "睁眼苏醒"},
		{"type": "line", "source": 19, "speaker": "旁白", "text": "四周是一片巨大的草地。"},
		{"type": "line", "source": 20, "speaker": "旁白", "text": "没有房子。"},
		{"type": "line", "source": 21, "speaker": "旁白", "text": "没有道路。"},
		{"type": "line", "source": 22, "speaker": "旁白", "text": "也没有城市。"},
		{"type": "line", "source": 23, "speaker": "旁白", "text": "只有一望无际的草，随着风一层一层地起伏。"},
		{"type": "line", "source": 24, "speaker": "旁白", "text": "天空很低，月亮却很大。无数巨大的星星悬浮在半空，像漂浮在水中的灯。"},
		{"type": "line", "source": 25, "speaker": "旁白", "text": "远处的地平线上，长着一些巨大而陌生的植物。"},
		{"type": "line", "source": 26, "speaker": "旁白", "text": "它们像树，却没有树干，细长的枝条悬在空中，随着风慢慢摆动。"},
		{"type": "line", "source": 27, "speaker": "旁白", "text": "草地里散落着许多微弱发光的小东西。"},
		{"type": "line", "source": 28, "speaker": "旁白", "text": "像萤火虫，又像星星落在了地上。"},
		{"type": "line", "source": 30, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 31, "speaker": "旁白", "text": "远处传来一个声音。"},
		{"type": "line", "source": 32, "speaker": "？？？", "text": "你醒了？"},
		{"type": "camera", "source": 34, "id": "shot_02_turn", "status": "听声回头"},
		{"type": "line", "source": 37, "speaker": "小凌", "text": "（回头）", "stage_direction": true},
		{"type": "cg", "source": 37, "art_scene_index": 2, "name": "奇妙夜场景2", "asset": "res://assets/cutscenes/mystic_night/02_girl_on_rock.png", "video_asset": "res://assets/cutscenes/mystic_night/02_girl_on_rock_transition.ogv", "video_end_source": 60},
		{"type": "line", "source": 37, "speaker": "旁白", "text": "一个短发女孩坐在不远处的大石头上。"},
		{"type": "line", "source": 38, "speaker": "旁白", "text": "她的头发被风轻轻吹动。女孩手里拿着一根不知道从哪里捡来的长草，正漫不经心地拨弄脚边发光的小生物。"},
		{"type": "line", "source": 39, "speaker": "旁白", "text": "她静静面对着小凌。"},
		{"type": "line", "source": 40, "speaker": "小凌", "text": "（后退一步）", "stage_direction": true},
		{"type": "line", "source": 40, "speaker": "小凌", "text": "你是谁？"},
		{"type": "line", "source": 41, "speaker": "女孩", "text": "不知道。"},
		{"type": "line", "source": 42, "speaker": "小凌", "text": "……什么？"},
		{"type": "line", "source": 43, "speaker": "女孩", "text": "我也不知道自己是谁。"},
		{"type": "line", "source": 44, "speaker": "小凌", "text": "那你怎么会在这里？"},
		{"type": "line", "source": 45, "speaker": "女孩", "text": "可能是因为，我迷路了。"},
		{"type": "line", "source": 46, "speaker": "小凌", "text": "你迷路了？"},
		{"type": "line", "source": 48, "speaker": "女孩", "text": "（点点头）", "stage_direction": true},
		{"type": "line", "source": 48, "speaker": "旁白", "text": "她从草坡上跳下来。"},
		{"type": "line", "source": 49, "speaker": "旁白", "text": "落地的时候，周围的草突然亮了一圈。"},
		{"type": "camera", "source": 50, "id": "shot_03_landing_pulse", "status": "落地光圈"},
		{"type": "line", "source": 51, "speaker": "旁白", "text": "女孩朝前走去。"},
		{"type": "line", "source": 52, "speaker": "女孩", "text": "走吗？"},
		{"type": "line", "source": 53, "speaker": "小凌", "text": "去哪？"},
		{"type": "line", "source": 54, "speaker": "女孩", "text": "不知道。"},
		{"type": "line", "source": 55, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 56, "speaker": "女孩", "text": "所以才要走啊。"},
		{"type": "line", "source": 58, "speaker": "小凌", "text": "（犹豫）", "stage_direction": true},
		{"type": "interaction", "source": 58, "id": "follow_girl", "prompt": "跟上去", "status": "继续跟随女孩。"},
		{"type": "line", "source": 60, "speaker": "旁白", "text": "两个人一前一后走在草地上。"},
		{"type": "cg", "source": 61, "art_scene_index": 3, "name": "奇妙夜拉手图", "asset": "res://assets/cutscenes/mystic_night/03_follow.jpg"},
		{"type": "camera", "source": 61, "id": "shot_04_walk", "status": "行走晃动"},
		{"type": "line", "source": 61, "speaker": "旁白", "text": "风很大。"},
		{"type": "line", "source": 62, "speaker": "旁白", "text": "发光的小生物从她们脚边飞起来，又落回草丛。"},
		{"type": "line", "source": 63, "speaker": "旁白", "text": "远处偶尔传来不知道什么动物的叫声。"},
		{"type": "line", "source": 63, "speaker": "旁白", "text": "前面是一片很高的草坡。"},
		{"type": "line", "source": 64, "speaker": "女孩", "text": "回头", "stage_direction": true},
		{"type": "line", "source": 64, "speaker": "女孩", "text": "你刚才在哭吗？"},
		{"type": "line", "source": 66, "speaker": "小凌", "text": "（摸了一下自己的脸）", "stage_direction": true},
		{"type": "line", "source": 66, "speaker": "小凌", "text": "没有。"},
		{"type": "line", "source": 67, "speaker": "女孩", "text": "哦。"},
		{"type": "line", "source": 68, "speaker": "旁白", "text": "女孩没有继续追问。"},
		{"type": "line", "source": 69, "speaker": "旁白", "text": "又走了一会儿。"},
		{"type": "line", "source": 70, "speaker": "小凌", "text": "……其实有一点。"},
		{"type": "cg", "source": 71, "art_scene_index": 4, "name": "奇妙夜鸟图", "asset": "res://assets/cutscenes/mystic_night/04_moon_creatures.jpg", "transition": "down_dissolve"},
		{"type": "line", "source": 71, "speaker": "旁白", "text": "她们终于爬到草坡的顶端，眼前突然开阔，整个草原都在脚下，远处的山像漂浮在云里。"},
		{"type": "camera", "source": 72, "id": "shot_05_reveal", "status": "草坡视野展开"},
		{"type": "line", "source": 73, "speaker": "旁白", "text": "天空中有一些巨大的、缓慢游动的发光生物，它们像鲸鱼一样游过云层。"},
		{"type": "line", "source": 74, "speaker": "小凌", "text": "……好漂亮。"},
		{"type": "line", "source": 75, "speaker": "女孩", "text": "嗯。"},
		{"type": "line", "source": 76, "speaker": "小凌", "text": "你说，如果有些事情已经决定好了，是不是就不应该再想了。"},
		{"type": "line", "source": 77, "speaker": "女孩", "text": "……"},
		{"type": "line", "source": 78, "speaker": "女孩", "text": "你觉得呢？"},
		{"type": "line", "source": 79, "speaker": "小凌", "text": "我不知道。"},
		{"type": "line", "source": 80, "speaker": "女孩", "text": "既然还会想，就说明它还没有真的决定。"},
		{"type": "line", "source": 81, "speaker": "心理", "text": "小凌看着女孩的背影，突然觉得有些说不清楚的感觉从心里撒出来。"},
		{"type": "line", "source": 82, "speaker": "小凌", "text": "（抬起头）", "stage_direction": true},
		{"type": "line", "source": 82, "speaker": "小凌", "text": "我明天要结婚了。"},
		{"type": "line", "source": 83, "speaker": "心理", "text": "小凌自己也不知道自己为什么会说出来。"},
		{"type": "line", "source": 84, "speaker": "旁白", "text": "她低头看着脚下的草。"},
		{"type": "line", "source": 85, "speaker": "小凌", "text": "其实……我有一点不想去。"},
		{"type": "line", "source": 86, "speaker": "旁白", "text": "女孩没有问为什么，只是轻轻“嗯”了一声。"},
		{"type": "cg", "source": 89, "art_scene_index": 5, "name": "奇妙夜星星图", "asset": "res://assets/cutscenes/mystic_night/05_falling_stars.png", "video_asset": "res://assets/cutscenes/mystic_night/05_falling_stars_transition.ogv", "video_end_source": 94, "transition": "down_dissolve"},
		{"type": "line", "source": 89, "speaker": "旁白", "text": "一群像鸟一样的生物从二人头顶飞过，在飞到最高处时变成一颗颗发光的星星洒落下来。"},
		{"type": "line", "source": 92, "speaker": "旁白", "text": "女孩随手摘了一朵会随着人的靠近而闭合的花送给小凌。"},
		{"type": "cg", "source": 95, "art_scene_index": 6, "name": "奇妙夜送花图", "asset": "res://assets/cutscenes/mystic_night/06_flower.jpg"},
		{"type": "line", "source": 95, "speaker": "旁白", "text": "两个人没有再谈些什么，她们只是在草原上走。"},
		{"type": "cg", "source": 96, "art_scene_index": 7, "name": "奇妙夜追逐图", "asset": "res://assets/cutscenes/mystic_night/07_run.jpg", "transition": "dissolve"},
		{"type": "camera", "source": 96, "id": "shot_06_run", "status": "第一人称跑动"},
		{"type": "line", "source": 96, "speaker": "旁白", "text": "一只发光的小动物突然从高高的草丛里钻了出来，沿着草叶间飞快地跑远。"},
		{"type": "line", "source": 96, "speaker": "旁白", "text": "女孩和小凌对视一眼，不约而同地追了上去。"},
		{"type": "line", "source": 96, "speaker": "旁白", "text": "两个人一前一后穿过大片起伏的高草，发光的小动物时隐时现，像一颗在草丛里跳动的小星星。"},
		{"type": "cg", "source": 96, "art_scene_index": 8, "name": "奇妙夜发光动物图", "asset": "res://assets/cutscenes/mystic_night/07_glowing_animal.jpg", "transition": "dissolve"},
		{"type": "line", "source": 96, "speaker": "旁白", "text": "女孩忽然放慢脚步，伸出双手，小心翼翼地将它捧在掌心。"},
		{"type": "line", "source": 96, "speaker": "旁白", "text": "小动物蜷缩起来，身体一点点亮起蓝色的光。"},
		{"type": "line", "source": 96, "speaker": "旁白", "text": "光映在女孩的脸上，也照亮了小凌的眼睛。"},
		{"type": "line", "source": 96, "speaker": "旁白", "text": "女孩低头看着掌心的小动物，忍不住笑了。"},
		{"type": "cg", "source": 96, "art_scene_index": 9, "name": "奇妙夜湿地图", "asset": "res://assets/cutscenes/mystic_night/08_wetland.jpg", "transition": "dissolve"},
		{"type": "line", "source": 99, "speaker": "旁白", "text": "不知道走了多久。"},
		{"type": "line", "source": 100, "speaker": "旁白", "text": "草地开始慢慢变矮，风也停了。前方的地面逐渐变得潮湿，一些陌生的植物从草丛中长出来，它们的叶片巨大，边缘泛着幽蓝色的光。"},
		{"type": "line", "source": 101, "speaker": "旁白", "text": "小凌踩过一片落叶。"},
		{"type": "cg", "source": 105, "art_scene_index": 10, "name": "奇妙夜森林轮廓图", "asset": "res://assets/cutscenes/mystic_night/09_forest_edge.jpg", "video_asset": "res://assets/cutscenes/mystic_night/10_forest_transition.ogv", "video_end_source": 133},
		{"type": "camera", "source": 106, "id": "shot_07_forest_push", "status": "森林吸引视线"},
		{"type": "line", "source": 107, "speaker": "旁白", "text": "远处的地平线上，出现了一片巨大的黑色轮廓。"},
		{"type": "line", "source": 108, "speaker": "旁白", "text": "最开始像一座山，又像一片压低的乌云。"},
		{"type": "line", "source": 109, "speaker": "旁白", "text": "随着她们继续向前，那些轮廓越来越清晰。"},
		{"type": "line", "source": 110, "speaker": "旁白", "text": "是一片森林。"},
		{"type": "line", "source": 111, "speaker": "旁白", "text": "树木高得看不见顶，无数粗大的枝干彼此缠绕，像是从地面一直生长到了天空。森林里没有光。没有风。甚至听不见草叶的声音。只有一些很远、很轻的虫鸣"},
		{"type": "line", "source": 112, "speaker": "旁白", "text": "小凌停下脚步。"},
		{"type": "line", "source": 113, "speaker": "旁白", "text": "女孩也停下来。"},
		{"type": "line", "source": 114, "speaker": "旁白", "text": "两个人望着那片黑暗。"},
		{"type": "line", "source": 115, "speaker": "小凌", "text": "那里……也是这里的一部分吗？"},
		{"type": "line", "source": 116, "speaker": "旁白", "text": "女孩没有回答。"},
		{"type": "line", "source": 117, "speaker": "旁白", "text": "她只是安静地面向那片森林。"},
		{"type": "line", "source": 118, "speaker": "女孩", "text": "……。"},
		{"type": "line", "source": 119, "speaker": "女孩", "text": "我们换条路吧。"},
		{"type": "line", "source": 121, "speaker": "小凌", "text": "为什么？"},
		{"type": "line", "source": 122, "speaker": "女孩", "text": "（看向森林深处）", "stage_direction": true},
		{"type": "line", "source": 122, "speaker": "小凌", "text": "（向前走了一步）", "stage_direction": true},
		{"type": "line", "source": 122, "speaker": "女孩", "text": "……"},
		{"type": "line", "source": 124, "speaker": "心理", "text": "小凌站在那里，不知道为什么，那片黑暗却好像正在叫她，很轻，很远，却比刚才草原上的任何声音都清楚。"},
		{"type": "line", "source": 126, "speaker": "女孩", "text": "别去。"},
		{"type": "camera", "source": 127, "id": "shot_08_still", "status": "“别去”静止"},
		{"type": "line", "source": 130, "speaker": "旁白", "text": "女孩第一次没有继续向前，身体微微绷紧，站在原地。"},
		{"type": "line", "source": 131, "speaker": "女孩", "text": "那里和这里不一样。"},
		{"type": "line", "source": 132, "speaker": "小凌", "text": "哪里不一样？"},
		{"type": "cg", "source": 134, "art_scene_index": 11, "name": "奇妙夜别去图", "asset": "res://assets/cutscenes/mystic_night/10_dont_go.png"},
		{"type": "line", "source": 134, "speaker": "女孩", "text": "（没有回答我，只是摇了摇头）", "stage_direction": true},
		{"type": "line", "source": 134, "speaker": "旁白", "text": "小凌重新看向森林，黑暗之中，似乎有什么东西一闪而过，她没有看清。"},
		{"type": "line", "source": 136, "speaker": "心理", "text": "但她突然很想知道——那里究竟有什么。"},
		{"type": "line", "source": 137, "speaker": "小凌", "text": "我想去看看。"},
		{"type": "cg", "source": 138, "art_scene_index": 12, "name": "奇妙夜女孩身影图", "asset": "res://assets/cutscenes/mystic_night/11_last_look.png", "transition": "dissolve"},
		{"type": "line", "source": 138, "speaker": "旁白", "text": "女孩没有再阻止她，只是站在原地。"},
		{"type": "line", "source": 139, "speaker": "旁白", "text": "小凌慢慢走向森林，草地在她脚下逐渐消失，取而代之的是潮湿的泥土和厚厚的落叶。身后的草原越来越亮，眼前的森林越来越黑。"},
		{"type": "camera", "source": 143, "id": "shot_09_last_look", "status": "最后回望与转身"},
		{"type": "line", "source": 144, "speaker": "旁白", "text": "女孩还站在那里。她没有说话，只是远远地朝向小凌。"},
		{"type": "cg", "source": 146, "art_scene_index": 0, "name": "黑屏", "asset": ""},
		{"type": "endpoint", "source": 146, "id": "MYSTIC_NIGHT_END", "text": "请闭上眼睛", "next": "森林正片 EYE_OPEN"},
	]
