class_name DarkForestStoryData
extends RefCounted


static func get_events() -> Array[Dictionary]:
	return [
		# 环境背景图0 -> 环境背景图1
		{"type": "scene", "source": 29, "name": "环境背景图0"},
		{"type": "audio", "source": 29, "action": "start", "stream": "forest_bgm_dark_forest", "status": "黑暗森林主题 BGM 起"},
		{"type": "transition", "source": 49, "id": "EYE_OPEN", "to": "环境背景图1", "status": "睁眼显现：可见区域由中心缓慢扩展。"},
		{"type": "interaction", "source": 51, "id": "light_hover", "prompt": "把鼠标持续停留在右侧光源区域"},
		{"type": "action", "source": 52, "id": "light_trigger", "status": "光源消失；锁定操作；黑色遮罩覆盖约80%。"},
		{"type": "wait", "source": 52, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "effect", "source": 53, "id": "heart_light", "status": "阿麦心脏位置生成独立柔和径向光，覆盖约40%。"},
		{"type": "line", "source": 54, "speaker": "心理（警觉）", "text": "这是什么地方？"},
		{"type": "line", "source": 55, "speaker": "阿麦", "text": "你想让这里是什么地方，这里就是什么地方。"},
		{"type": "action", "source": 56, "id": "xiaoling_back_two", "status": "小凌连续后退两步；完成后黑色遮罩逐渐减弱。"},
		{"type": "line", "source": 57, "speaker": "旁白", "text": "这里的树并不是笔直冲天的，每棵树以奇怪的方式和其他树错综复杂地交织着。脚边的地上铺满了腐叶，有类似刺猬的小动物从她脚边跑过，远处……小凌眨了眨眼，光太暗了，远处看不清"},
		{"type": "action", "source": 58, "id": "amai_firefly_gesture", "status": "阿麦冲远处做手势；萤火虫排成一列并亮起道路。"},
		{"type": "transition", "source": 59, "id": "FIREFLY_GUIDE", "to": "环境背景图2", "status": "萤火虫向森林深处连续飞去；站位与朝向保持连续。"},

		# 环境背景图2
		{"type": "line", "source": 61, "speaker": "阿麦", "text": "走吧。"},
		{"type": "line", "source": 62, "speaker": "小凌", "text": "去哪儿？"},
		{"type": "line", "source": 63, "speaker": "旁白", "text": "阿麦没有回答，也没有看她，径直往前走", "stage_cue": "amai_walk_waypoint"},
		{"type": "action", "source": 64, "id": "amai_walk_waypoint", "status": "阿麦向右缓慢步行至画面中右侧 waypoint，随后切回 Idle。"},
		{"type": "line", "source": 65, "speaker": "小凌", "text": "我又不知道你是谁，我为什么要跟你去。"},
		{"type": "action", "source": 66, "id": "amai_stop_idle", "status": "阿麦立即停止位移，由 Walk 切换为 Idle。"},
		{"type": "line", "source": 67, "speaker": "旁白", "text": "阿麦的脸颊在黑暗下棱角分明，但你仍然看不清他的脸。"},
		{"type": "action", "source": 68, "id": "amai_second_gesture", "status": "阿麦抬起手，轻轻做出另一个手势。"},
		{"type": "line", "source": 69, "speaker": "旁白", "text": "刚才排成一列的萤火虫忽然散开，向森林深处飞去。黑暗重新合拢，只有一颗萤火虫停在你面前，微弱地闪烁着。"},
		{"type": "effect", "source": 70, "id": "single_firefly", "status": "一个光点沿轻微弧线飞到小凌面前，并保持呼吸闪烁。"},
		{"type": "line", "source": 71, "speaker": "阿麦", "text": "你说得对。"},
		{"type": "line", "source": 72, "speaker": "心理", "text": "有些意外"},
		{"type": "line", "source": 73, "speaker": "阿麦", "text": "你不应该跟一个不知道是谁的人走。"},
		{"type": "line", "source": 74, "speaker": "小凌", "text": "那你还让我跟你走？"},
		{"type": "action", "source": 75, "id": "amai_smile", "status": "阿麦笑。"},
		{"type": "line", "source": 76, "speaker": "阿麦", "text": "我只是带路。"},
		{"type": "line", "source": 77, "speaker": "旁白", "text": "他转过身，萤火虫重新排列成一条线，阿麦沿着萤火虫照亮的小路慢慢往前走。走了几步，他停下来，没有回头。", "stage_cue": "amai_walk_few_steps"},
		{"type": "line", "source": 78, "speaker": "阿麦", "text": "你可以不跟。"},
		{"type": "line", "source": 79, "speaker": "旁白", "text": "森林里又传来窸窸窣窣的声音。树枝上，一只眼睛圆溜溜的小动物探出脑袋，好奇地看着她。森林深处似乎有水源的痕迹，有什么东西在水里扑腾了一下。"},
		{"type": "action", "source": 80, "id": "xiaoling_look_back", "status": "小凌看着阿麦的背影。"},
		{"type": "line", "source": 81, "speaker": "心理", "text": "不知道为什么，她突然觉得——这个地方好像没有人在催她。没有人告诉她应该去哪。也没有人告诉她，这条路才是正确的。"},
		{"type": "line", "source": 82, "speaker": "心理", "text": "犹豫…"},
		{"type": "choice", "source": 83, "id": "follow_choice", "prompt": "走 / 不走？", "options": [{"id": "follow", "text": "走"}, {"id": "stay", "text": "不走"}], "routes": {"follow": "follow_move", "stay": "stay_move"}},
		{"type": "label", "id": "stay_move"},
		{"type": "movement", "source": 84, "id": "follow_right", "prompt": "A / ← 检查来路；D / → 往阿麦方向走", "allow_reverse": true},
		{"type": "goto", "target": "walk_narration"},
		{"type": "label", "id": "follow_move"},
		{"type": "movement", "source": 84, "id": "follow_right", "prompt": "按 D / → 往阿麦方向走", "allow_reverse": false},
		{"type": "label", "id": "walk_narration"},
		{"type": "line", "source": 88, "speaker": "旁白", "text": "两个人一前一后走在森林里。路越来越窄。地形开始慢慢上坡。周围的障碍和树木越来越奇怪。直到，眼前出现了一条岔路。", "stage_cue": "both_walk_to_fork"},
		{"type": "transition", "source": 89, "id": "WALK_CONTINUE", "to": "环境背景图3", "status": "两人保持 Walk 向右；背景2左移，背景3从右侧接入，再自然减速至 Idle。"},

		# 环境背景图3
		{"type": "line", "source": 91, "speaker": "旁白", "text": "左边是一条铺满花瓣的静谧小路。右边则传来潺潺的水声，黑漆漆的，看不清里面有什么。"},
		{"type": "line", "source": 92, "speaker": "阿麦", "text": "你想走哪边？"},
		{"type": "line", "source": 93, "speaker": "小凌", "text": "不是你带路吗？"},
		{"type": "line", "source": 94, "speaker": "阿麦", "text": "这里没有规定谁带路。"},
		{"type": "line", "source": 95, "speaker": "小凌", "text": "……"},
		{"type": "action", "source": 96, "id": "xiaoling_look_left", "status": "小凌看向左边。"},
		{"type": "line", "source": 97, "speaker": "小凌", "text": "那就左边吧。"},
		{"type": "line", "source": 98, "speaker": "阿麦", "text": "……。"},
		{"type": "line", "source": 99, "speaker": "小凌", "text": "怎么了？"},
		{"type": "line", "source": 100, "speaker": "阿麦", "text": "你真的想走左边？"},
		{"type": "line", "source": 101, "speaker": "小凌", "text": "嗯。"},
		{"type": "line", "source": 102, "speaker": "阿麦", "text": "还是因为它看起来比较安全？"},
		{"type": "line", "source": 103, "speaker": "小凌", "text": "……。"},
		{"type": "action", "source": 104, "id": "amai_point_right", "status": "阿麦指了指右边。"},
		{"type": "line", "source": 105, "speaker": "旁白", "text": "阿麦指了指右边。"},
		{"type": "line", "source": 105, "speaker": "阿麦", "text": "那边有瀑布。"},
		{"type": "line", "source": 106, "speaker": "小凌", "text": "所以？"},
		{"type": "line", "source": 107, "speaker": "阿麦", "text": "我们可以下去。"},
		{"type": "line", "source": 108, "speaker": "小凌", "text": "下水？"},
		{"type": "line", "source": 109, "speaker": "阿麦", "text": "嗯。"},
		{"type": "line", "source": 110, "speaker": "小凌", "text": "不行。"},
		{"type": "line", "source": 111, "speaker": "阿麦", "text": "为什么？"},
		{"type": "line", "source": 112, "speaker": "小凌", "text": "会弄湿衣服。"},
		{"type": "action", "source": 113, "id": "amai_look_clothes", "status": "阿麦低头看了一眼她的衣服。"},
		{"type": "line", "source": 113, "speaker": "阿麦", "text": "那又怎样？"},
		{"type": "line", "source": 114, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 115, "speaker": "旁白", "text": "阿麦忽然笑起来。"},
		{"type": "line", "source": 116, "speaker": "旁白", "text": "他没有再问。"},
		{"type": "line", "source": 117, "speaker": "旁白", "text": "只是朝着右边的路跑了起来", "stage_cue": "amai_run_ahead"},
		{"type": "action", "source": 118, "id": "amai_run_entry", "status": "阿麦切换为 Run，向右跑至 ForestRun 入口并保持奔跑状态。"},
		{"type": "line", "source": 119, "speaker": "小凌", "text": "喂！"},
		{"type": "action", "source": 120, "id": "xiaoling_run_follow", "status": "小凌跑着跟了上去。"},
		{"type": "movement", "source": 121, "id": "forest_run_entry", "prompt": "按 D / → 追赶阿麦并进入 ForestRun 接口", "allow_reverse": false},
		{"type": "module", "source": 122, "id": "ForestRun", "scene": "res://scenes/forest/parkour/parkour_prototype.tscn", "completion_signal": "parkour_completed", "result": "success"},
		{"type": "transition", "source": 123, "id": "FOREST_RUN_EXIT", "to": "环境背景图4", "status": "保持向右奔跑切入背景4；阿麦先减速，小凌追上后两人转为 Idle。"},
		{"type": "audio", "source": 123, "action": "stop", "stream": "forest_bgm_dark_forest", "status": "黑暗森林主题 BGM 淡出"},
		{"type": "audio", "source": 123, "action": "start", "stream": "forest_bgm_parkour", "status": "森林跑酷惊险奇幻 BGM 起"},

		# 环境背景图4与瀑布
		{"type": "line", "source": 125, "speaker": "旁白", "text": "小凌跑了很久终于追上了阿麦，他们来到了瀑布顶端。"},
		{"type": "line", "source": 126, "speaker": "旁白", "text": "他们站在瀑布的顶端一起向下望，依旧看不到底。"},
		{"type": "line", "source": 127, "speaker": "旁白", "text": "阿麦回头。"},
		{"type": "action", "source": 127, "id": "amai_turn_back", "status": "阿麦回头。"},
		{"type": "line", "source": 127, "speaker": "阿麦", "text": "你怕吗？"},
		{"type": "line", "source": 128, "speaker": "小凌", "text": "怕什么。"},
		{"type": "line", "source": 129, "speaker": "阿麦", "text": "跳水。"},
		{"type": "line", "source": 130, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 131, "speaker": "阿麦", "text": "要不要试试看？"},
		{"type": "line", "source": 132, "speaker": "小凌", "text": "我不会游泳。"},
		{"type": "line", "source": 133, "speaker": "阿麦", "text": "没关系，我会接住你。你不相信我吗？"},
		{"type": "line", "source": 134, "speaker": "心理", "text": "犹豫"},
		{"type": "line", "source": 135, "speaker": "旁白", "text": "阿麦索性直接跳了下去。"},
		{"type": "interaction", "source": 136, "id": "jump_button", "prompt": "点击按钮，让小凌跳水"},
		{"type": "transition", "source": 138, "id": "WATERFALL_JUMP", "to": "人物剧情图1", "status": "锁定操作；向下离场与轻微镜头 push；水雾覆盖后切换剧情图。"},
		{"type": "line", "source": 140, "speaker": "旁白", "text": "阿麦接住了小凌。"},
		{"type": "action", "source": 140, "id": "switch_touch_chest_cg", "status": "阿麦接住小凌后，从瀑布下 CG 柔和切换到摸心脏 CG。"},
		{"type": "line", "source": 140, "speaker": "旁白", "text": "小凌看到他心脏中闪烁的光，如同自己的呼吸一般。小凌忍不住触摸那束光，光线散出一团光丝缠绕着小凌的手。"},
		{"type": "module_skip", "source": 141, "id": "WaterfallInteraction", "result": "continue"},
		{"type": "action", "source": 142, "id": "switch_wet_states", "status": "小凌1切换到小凌2，阿麦1切换到阿麦2。"},
		{"type": "line", "source": 144, "speaker": "旁白", "text": "阿麦向上看着刚才跳下来的瀑布顶端。"},
		{"type": "action", "source": 145, "id": "amai_look_up", "status": "阿麦向上看刚才跳下来的瀑布顶端。"},
		{"type": "line", "source": 145, "speaker": "阿麦", "text": "你看……"},
		{"type": "line", "source": 146, "speaker": "旁白", "text": "溪水在月光下闪着细碎的光。"},
		{"type": "line", "source": 147, "speaker": "阿麦", "text": "什么都没有发生。"},
		{"type": "line", "source": 148, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 149, "speaker": "阿麦", "text": "衣服湿了可以晒干。"},
		{"type": "line", "source": 150, "speaker": "小凌", "text": "你真是个怪人。"},
		{"type": "line", "source": 151, "speaker": "旁白", "text": "阿麦低头看着水里的自己。"},
		{"type": "action", "source": 151, "id": "amai_look_reflection", "status": "阿麦低头看着水里的自己。"},
		{"type": "line", "source": 151, "speaker": "阿麦", "text": "所以你对自己可以不用这么严格。"},
		{"type": "line", "source": 152, "speaker": "小凌", "text": "你说什么？"},
		{"type": "line", "source": 153, "speaker": "旁白", "text": "阿麦抬起头看着小凌。"},
		{"type": "action", "source": 153, "id": "amai_look_xiaoling", "status": "阿麦抬起头看着小凌。"},
		{"type": "line", "source": 153, "speaker": "阿麦", "text": "想做什么就做什么。"},
		{"type": "line", "source": 154, "speaker": "小凌", "text": "哪有那么简单。"},
		{"type": "line", "source": 155, "speaker": "阿麦", "text": "为什么不简单？"},
		{"type": "line", "source": 156, "speaker": "小凌", "text": "因为……"},
		{"type": "module", "source": 157, "id": "TextInput", "scene": "res://levels/minigames/text_input.tscn", "completion_signal": "finished", "result": "success"},
		{"type": "line", "source": 158, "speaker": "旁白", "text": "阿麦拉起小凌的手。"},
		{"type": "action", "source": 158, "id": "amai_take_hand", "status": "阿麦拉起小凌的手。"},
		{"type": "line", "source": 158, "speaker": "阿麦", "text": "那就只做你最想做的那件事"},
		{"type": "action", "source": 159, "id": "switch_stream_states", "status": "小凌2切换到小凌3，阿麦2切换到阿麦3。"},
		{"type": "transition", "source": 161, "id": "STREAM_WALK", "to": "环境背景图6", "status": "光丝与水面反光减弱；阿麦先从左侧步入，小凌随后进入并继续前行。"},

		# 环境背景图6与神秘湖
		{"type": "line", "source": 163, "speaker": "旁白", "text": "他们顺着小溪旁的路往前走，来到一个巨大的神秘湖面前。湖水深不见底，像深渊，什么都看不见。"},
		{"type": "line", "source": 164, "speaker": "旁白", "text": "湖中散落着一块块巨大的形状各异的黑色石头。湖对岸的森林边缘长着一片尖尖的红色植物，像火一样在黑暗中摇曳。"},
		{"type": "line", "source": 166, "speaker": "旁白", "text": "阿麦走到岸边。"},
		{"type": "action", "source": 167, "id": "lake_approach", "status": "承接站位与朝向；阿麦走向湖岸 waypoint，小凌恢复左右控制。"},
		{"type": "movement", "source": 167, "id": "lake_trigger", "prompt": "按 D / → 靠近湖岸的剧情 trigger", "allow_reverse": false},
		{"type": "line", "source": 168, "speaker": "小凌", "text": "你干什么？"},
		{"type": "line", "source": 169, "speaker": "旁白", "text": "阿麦没有回答。他踩上一块石头。再跳到下一块。轻轻松松地到了湖面中央。"},
		{"type": "action", "source": 170, "id": "amai_stone_route", "status": "阿麦按预设石头顺序自动移动；小凌被 invisible boundary 限制在岸边。"},
		{"type": "line", "source": 172, "speaker": "小凌", "text": "那里很滑。"},
		{"type": "action", "source": 173, "id": "amai_turn_lake", "status": "阿麦回头。"},
		{"type": "line", "source": 174, "speaker": "阿麦", "text": "所以呢？"},
		{"type": "line", "source": 175, "speaker": "小凌", "text": "会掉下去。"},
		{"type": "action", "source": 176, "id": "amai_laugh", "status": "阿麦笑了。"},
		{"type": "line", "source": 176, "speaker": "阿麦", "text": "那就掉下去。"},
		{"type": "line", "source": 177, "speaker": "小凌", "text": "……"},
		{"type": "action", "source": 178, "id": "amai_open_arms", "status": "阿麦站在水中央，张开双臂。"},
		{"type": "line", "source": 179, "speaker": "旁白", "text": "阿麦站在水中央，张开双臂。"},
		{"type": "line", "source": 179, "speaker": "阿麦", "text": "你不想试试吗？"},
		{"type": "choice", "source": 181, "id": "lake_choice", "prompt": "想试试吗？", "options": [{"id": "lake_yes", "text": "想"}, {"id": "lake_no", "text": "不想"}], "routes": {"lake_yes": "lake_yes_route", "lake_no": "lake_no_route"}},
		{"type": "label", "id": "lake_yes_route"},
		{"type": "goto", "target": "lake_jump_entry"},
		{"type": "label", "id": "lake_no_route"},
		{"type": "line", "source": 183, "speaker": "小凌", "text": "不想。"},
		{"type": "line", "source": 184, "speaker": "阿麦", "text": "真的？"},
		{"type": "line", "source": 185, "speaker": "小凌", "text": "真的。"},
		{"type": "line", "source": 186, "speaker": "旁白", "text": "阿麦突然跳进水里。"},
		{"type": "action", "source": 187, "id": "amai_dive", "status": "阿麦快速向下离开；进入水面后隐藏；镜头短促轻微震动。"},
		{"type": "audio", "source": 188, "cue": "扑通。"},
		{"type": "action", "source": 189, "id": "xiaoling_back_lake", "status": "短暂锁定操作；小凌平滑后退两步，随后停在 Idle。"},
		{"type": "line", "source": 190, "speaker": "旁白", "text": "下一秒——阿麦从水里冒出来，头发湿漉漉地贴在脸上"},
		{"type": "line", "source": 191, "speaker": "阿麦", "text": "不来试试吗？"},
		{"type": "label", "id": "lake_jump_entry"},
		{"type": "line", "source": 192, "speaker": "旁白", "text": "小凌看着他，踏入了湖里。"},
		{"type": "module", "source": 193, "id": "LakeJump", "scene": "res://levels/river_jump.tscn", "completion_signal": "finished", "result": "success"},
		{"type": "label", "id": "drowning"},
		{"type": "audio", "source": 193, "action": "stop", "stream": "forest_bgm_parkour", "status": "森林跑酷 BGM 淡出"},
		{"type": "audio", "source": 193, "action": "start", "stream": "forest_bgm_8_30", "status": "8月30日 落水瞬间 BGM 起"},
		{"type": "line", "source": 195, "speaker": "旁白", "text": "小凌在水中不断下沉，闭上了眼"},
		{"type": "audio", "source": 195, "action": "stop_immediate", "stream": "forest_bgm_8_30", "status": "8月30日 掐断"},
		{"type": "audio", "source": 195, "action": "start", "stream": "forest_bgm_mystery_lake", "status": "神秘湖美丽危险 BGM 起"},
		{"type": "transition", "source": 196, "id": "DROWNING_CG", "to": "溺水图cg", "status": "切换至溺水图CG纯文字资源卡。"},
		{"type": "transition", "source": 199, "id": "DROWNING_EXIT", "to": "环境背景图7", "status": "溺水图CG结束，切换至环境背景图7。"},

		# 环境背景图7与神秘女孩
		{"type": "line", "source": 201, "speaker": "旁白", "text": "小凌猛地睁开眼。眼前是一片模糊的天空。"},
		{"type": "audio", "source": 201, "action": "stop", "stream": "forest_bgm_mystery_lake", "status": "神秘湖美丽危险 BGM 淡出"},
		{"type": "audio", "source": 201, "action": "start", "stream": "forest_bgm_heartbeat", "status": "心跳同步音乐自然长出 BGM 起（循环）"},
		{"type": "line", "source": 202, "speaker": "旁白", "text": "耳边传来水声。"},
		{"type": "line", "source": 203, "speaker": "旁白", "text": "她想动，却发现浑身都湿透了。"},
		{"type": "line", "source": 204, "speaker": "旁白", "text": "一个女孩正蹲在她身边，神情焦急。"},
		{"type": "line", "source": 205, "speaker": "旁白", "text": "小凌撑起身体，剧烈地咳嗽起来。"},
		{"type": "effect", "source": 206, "id": "cough_camera_shake", "status": "镜头进行 3 次轻微、不规则、短促震动。"},
		{"type": "line", "source": 208, "speaker": "小凌", "text": "有个人和我一起……"},
		{"type": "line", "source": 209, "speaker": "女孩", "text": "你差点死了。"},
		{"type": "line", "source": 210, "speaker": "旁白", "text": "小凌回头望向神秘湖。"},
		{"type": "line", "source": 211, "speaker": "旁白", "text": "湖面平静得像什么都没有发生过。"},
		{"type": "line", "source": 212, "speaker": "小凌", "text": "……他呢？"},
		{"type": "line", "source": 213, "speaker": "女孩", "text": "谁？"},
		{"type": "line", "source": 214, "speaker": "小凌", "text": "就是刚才和我在一起的人。"},
		{"type": "action", "source": 215, "id": "girl_frown", "status": "女孩皱眉。"},
		{"type": "action", "source": 216, "id": "girl_point_forest", "status": "女孩指了指湖对面的森林。"},
		{"type": "action", "source": 217, "id": "girl_offer_coat", "status": "女孩递外套。"},
		{"type": "line", "source": 218, "speaker": "女孩", "text": "（皱眉）"},
		{"type": "line", "source": 218, "speaker": "女孩", "text": "（递外套）"},
		{"type": "line", "source": 218, "speaker": "女孩", "text": "冷吗？"},
		{"type": "action", "source": 219, "id": "xiaoling_shake_head", "status": "小凌摇头。"},
		{"type": "wait", "source": 220, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "line", "source": 221, "speaker": "小凌", "text": "好像有一点。"},
		{"type": "action", "source": 222, "id": "girl_put_coat", "status": "女孩把外套披在小凌身上。"},
		{"type": "line", "source": 223, "speaker": "旁白", "text": "女孩把外套披在你身上。"},
		{"type": "line", "source": 223, "speaker": "旁白", "text": "两个人并排坐在湖边。谁也没有说话。"},
		{"type": "wait", "source": 224, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "line", "source": 225, "speaker": "小凌", "text": "你……一直跟着我？"},
		{"type": "line", "source": 226, "speaker": "女孩", "text": "嗯。"},
		{"type": "line", "source": 227, "speaker": "小凌", "text": "为什么?"},
		{"type": "line", "source": 228, "speaker": "女孩", "text": "因为……有点担心。"},
		{"type": "line", "source": 229, "speaker": "小凌", "text": "就这样？"},
		{"type": "line", "source": 230, "speaker": "女孩", "text": "不然呢？"},
		{"type": "action", "source": 231, "id": "xiaoling_look_lake", "status": "小凌低头看向湖面。"},
		{"type": "line", "source": 232, "speaker": "小凌", "text": "（低头看向湖面）"},
		{"type": "line", "source": 232, "speaker": "女孩", "text": "你刚才为什么跳下去？"},
		{"type": "line", "source": 233, "speaker": "小凌", "text": "……。"},
		{"type": "line", "source": 234, "speaker": "女孩", "text": "是因为他让你跳？"},
		{"type": "action", "source": 235, "id": "xiaoling_shake_head_2", "status": "小凌摇头。"},
		{"type": "line", "source": 236, "speaker": "小凌", "text": "（摇头）"},
		{"type": "line", "source": 236, "speaker": "女孩", "text": "那是因为你自己想跳？"},
		{"type": "action", "source": 237, "id": "xiaoling_shake_head_3", "status": "小凌摇头。"},
		{"type": "module", "source": 238, "id": "StarJar", "scene": "res://levels/minigames/firefly_bottle.tscn", "completion_signal": "finished", "result": "success"},
		{"type": "line", "source": 240, "speaker": "旁白", "text": "很久以后，小凌才小声说：我不知道。"},
		{"type": "line", "source": 241, "speaker": "女孩", "text": "不知道。"},
		{"type": "line", "source": 242, "speaker": "女孩", "text": "不知道以后做什么。"},
		{"type": "line", "source": 243, "speaker": "女孩", "text": "不知道喜不喜欢一个人。"},
		{"type": "line", "source": 244, "speaker": "女孩", "text": "不知道要不要留下。"},
		{"type": "line", "source": 245, "speaker": "女孩", "text": "不知道要不要往前走。"},
		{"type": "wait", "source": 246, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "line", "source": 247, "speaker": "女孩", "text": "不知道……自己到底想要什么？"},
		{"type": "action", "source": 248, "id": "xiaoling_hug_knees", "status": "小凌没有说话，把膝盖抱在怀里。"},
		{"type": "line", "source": 249, "speaker": "小凌", "text": "（没有说话，把膝盖抱在怀里）"},
		{"type": "line", "source": 249, "speaker": "小凌", "text": "你怎么知道？"},
		{"type": "line", "source": 250, "speaker": "女孩", "text": "猜的。"},
		{"type": "line", "source": 251, "speaker": "小凌", "text": "猜得也太准了。"},
		{"type": "action", "source": 252, "id": "girl_smile", "status": "女孩笑了一下。"},
		{"type": "line", "source": 252, "speaker": "女孩", "text": "（笑）因为我也这样"},
		{"type": "action", "source": 253, "id": "xiaoling_turn_girl", "status": "小凌转过头看向女孩。"},
		{"type": "line", "source": 254, "speaker": "小凌", "text": "（转头看向女孩）"},
		{"type": "action", "source": 254, "id": "girl_look_lake", "status": "女孩看着湖面。"},
		{"type": "line", "source": 254, "speaker": "女孩", "text": "（看着湖面）有一段时间，我特讨厌别人问我“以后想干什么”。"},
		{"type": "line", "source": 255, "speaker": "小凌", "text": "我也是。"},
		{"type": "line", "source": 256, "speaker": "女孩", "text": "每次有人问，我都觉得自己应该立刻找到那个正确答案。就好像，其他人都已经知道了，就我不知道一样。"},
		{"type": "line", "source": 257, "speaker": "小凌", "text": "对。"},
		{"type": "line", "source": 258, "speaker": "女孩", "text": "有人想早点买房子。"},
		{"type": "line", "source": 259, "speaker": "女孩", "text": "有人想早点结婚。"},
		{"type": "line", "source": 260, "speaker": "女孩", "text": "有人想早点生孩子。"},
		{"type": "line", "source": 261, "speaker": "女孩", "text": "有人想赚很多钱。"},
		{"type": "wait", "source": 262, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "line", "source": 263, "speaker": "女孩", "text": "只有我自己，好像什么都不知道。"},
		{"type": "line", "source": 264, "speaker": "小凌", "text": "……。"},
		{"type": "line", "source": 265, "speaker": "小凌", "text": "后来呢？"},
		{"type": "line", "source": 266, "speaker": "女孩", "text": "后来我选了一个。"},
		{"type": "line", "source": 267, "speaker": "小凌", "text": "是你想要的吗？"},
		{"type": "line", "source": 268, "speaker": "女孩", "text": "……"},
		{"type": "line", "source": 269, "speaker": "女孩", "text": "那时候的我，以为是。"},
		{"type": "line", "source": 270, "speaker": "小凌", "text": "那现在呢？"},
		{"type": "line", "source": 271, "speaker": "旁白", "text": "女孩没有回答。"},
		{"type": "line", "source": 272, "speaker": "旁白", "text": "她捡起脚边的一片叶子，在手里慢慢揉碎。"},
		{"type": "line", "source": 273, "speaker": "女孩", "text": "现在的我觉得……"},
		{"type": "line", "source": 274, "speaker": "女孩", "text": "可能没有哪一个选择，是从一开始就知道答案的。"},
		{"type": "line", "source": 275, "speaker": "小凌", "text": "那不是看起来很可怕吗？"},
		{"type": "line", "source": 276, "speaker": "女孩", "text": "是。"},
		{"type": "line", "source": 277, "speaker": "小凌", "text": "那你怎么敢选？"},
		{"type": "action", "source": 278, "id": "girl_laugh", "status": "女孩笑了。"},
		{"type": "line", "source": 278, "speaker": "女孩", "text": "（笑）我不敢。"},
		{"type": "line", "source": 279, "speaker": "女孩", "text": "所以我也有过很多晚上，躲在被子里偷偷哭。"},
		{"type": "line", "source": 280, "speaker": "小凌", "text": "你这么酷的女孩，也会干这种事吗？"},
		{"type": "line", "source": 281, "speaker": "女孩", "text": "我也羡慕过别人。"},
		{"type": "line", "source": 282, "speaker": "女孩", "text": "也想过，如果当初走另一条路，会不会更好。"},
		{"type": "line", "source": 283, "speaker": "女孩", "text": "也有过特别想逃走的时候。"},
		{"type": "line", "source": 284, "speaker": "小凌（轻轻问）", "text": "你逃了吗？"},
		{"type": "line", "source": 285, "speaker": "女孩", "text": "有时候。"},
		{"type": "line", "source": 286, "speaker": "小凌", "text": "后来呢？"},
		{"type": "line", "source": 287, "speaker": "女孩", "text": "后来又回来了。"},
		{"type": "line", "source": 288, "speaker": "小凌", "text": "为什么？"},
		{"type": "action", "source": 289, "id": "girl_deep_look", "status": "女孩深深地看着小凌。"},
		{"type": "line", "source": 290, "speaker": "旁白", "text": "女孩深深地看着小凌。"},
		{"type": "line", "source": 290, "speaker": "女孩", "text": "因为有一些东西，我还是舍不得。"},
		{"type": "line", "source": 291, "speaker": "旁白", "text": "小凌没有再问。"},
		{"type": "line", "source": 292, "speaker": "旁白", "text": "她忽然想到了思雨。"},
		{"type": "line", "source": 293, "speaker": "旁白", "text": "那个总是很忙、总是把生活安排得井井有条的人。"},
		{"type": "line", "source": 294, "speaker": "旁白", "text": "他真的不好吗？"},
		{"type": "line", "source": 295, "speaker": "旁白", "text": "好像也没有。"},
		{"type": "line", "source": 296, "speaker": "旁白", "text": "可她为什么还是觉得难过？"},
		{"type": "line", "source": 298, "speaker": "女孩", "text": "你喜欢他吗？"},
		{"type": "line", "source": 299, "speaker": "小凌", "text": "……"},
		{"type": "line", "source": 300, "speaker": "小凌", "text": "……喜欢吧。"},
		{"type": "line", "source": 301, "speaker": "女孩", "text": "那为什么还要逃？"},
		{"type": "action", "source": 302, "id": "xiaoling_long_silence", "status": "小凌沉默很久。"},
		{"type": "wait", "source": 302, "seconds": 3.5, "status": "按原文停留 3.5 秒。"},
		{"type": "line", "source": 303, "speaker": "小凌", "text": "可能，因为我怕。"},
		{"type": "line", "source": 304, "speaker": "女孩", "text": "怕什么？"},
		{"type": "line", "source": 305, "speaker": "小凌", "text": "怕以后就只能这样了。"},
		{"type": "line", "source": 306, "speaker": "女孩", "text": "哪样？"},
		{"type": "action", "source": 307, "id": "xiaoling_lower_head", "status": "小凌低下头。"},
		{"type": "action", "source": 308, "id": "subjective_soundscape", "status": "主观生活声音从分离到交织、达到顶点后统一静音；本版仅执行声音状态，不添加素材。"},
		{"type": "scene", "source": 309, "name": "主观内心背景图0"},
		{"type": "line", "source": 310, "speaker": "小凌", "text": "每天起床，做饭，工作，回家。"},
		{"type": "line", "source": 311, "speaker": "小凌", "text": "然后结婚。"},
		{"type": "line", "source": 312, "speaker": "小凌", "text": "然后可能有孩子。"},
		{"type": "line", "source": 313, "speaker": "小凌", "text": "然后……"},
		{"type": "wait", "source": 314, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "line", "source": 315, "speaker": "女孩", "text": "然后慢慢忘记自己是谁。"},
		{"type": "interaction", "source": 315, "id": "inner_objects_fan", "prompt": "张开手掌，水平往返挥扫，把这些挥开"},
		{"type": "line", "source": 316, "speaker": "旁白", "text": "小凌眼眶突然红了。"},
		{"type": "line", "source": 317, "speaker": "旁白", "text": "她看着女孩。"},
		{"type": "line", "source": 318, "speaker": "小凌", "text": "……你也会这样想吗？"},
		{"type": "line", "source": 319, "speaker": "女孩", "text": "（轻轻说）有时候"},
		{"type": "line", "source": 321, "speaker": "旁白", "text": "两个人靠在一起。"},
		{"type": "line", "source": 322, "speaker": "旁白", "text": "只是两个恰好坐在湖边的陌生女人，可是这一刻，她们却有一种奇怪的默契。"},
		{"type": "action", "source": 323, "id": "xiaoling_lean", "status": "小凌慢慢把头靠在女孩肩膀上。"},
		{"type": "action", "source": 324, "id": "girl_stiffen", "status": "女孩身体僵了一下，但没有躲开。"},
		{"type": "action", "source": 325, "id": "girl_lean", "status": "过了一会儿，女孩轻轻靠在小凌头上。"},
		{"type": "line", "source": 326, "speaker": "小凌", "text": "（慢慢把头靠在女孩肩膀上）"},
		{"type": "line", "source": 326, "speaker": "女孩", "text": "（身体僵了一下，却没有躲开）"},
		{"type": "line", "source": 326, "speaker": "旁白", "text": "过了一会儿，她轻轻靠在小凌头上。"},
		{"type": "line", "source": 326, "speaker": "女孩", "text": "其实我觉得……"},
		{"type": "line", "source": 327, "speaker": "小凌", "text": "嗯？"},
		{"type": "line", "source": 328, "speaker": "女孩", "text": "如果有一天，你真的选择了结婚。"},
		{"type": "line", "source": 329, "speaker": "女孩", "text": "也不要把自己弄丢了。"},
		{"type": "action", "source": 330, "id": "xiaoling_silent", "status": "小凌沉默。"},
		{"type": "line", "source": 331, "speaker": "女孩", "text": "如果有一天，你选择不结婚。"},
		{"type": "line", "source": 332, "speaker": "女孩", "text": "也不要觉得自己做错了。"},
		{"type": "line", "source": 333, "speaker": "女孩", "text": "如果有一天，你改变主意了。"},
		{"type": "line", "source": 334, "speaker": "女孩", "text": "也没关系。"},
		{"type": "wait", "source": 335, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "line", "source": 336, "speaker": "女孩", "text": "人不是一条路走到底的。"},
		{"type": "line", "source": 337, "speaker": "小凌（轻轻问）", "text": "那你呢？"},
		{"type": "action", "source": 338, "id": "girl_look_lake_2", "status": "女孩看着湖面。"},
		{"type": "wait", "source": 339, "seconds": 2.5, "status": "按原文停留 2.5 秒。"},
		{"type": "line", "source": 340, "speaker": "女孩", "text": "（看着湖面）"},
		{"type": "line", "source": 340, "speaker": "女孩", "text": "我啊……"},
		{"type": "line", "source": 341, "speaker": "女孩", "text": "我现在也还在找。"},
		{"type": "line", "source": 342, "speaker": "旁白", "text": "小凌抬起头。"},
		{"type": "line", "source": 343, "speaker": "旁白", "text": "女孩也转过来看她。"},
		{"type": "line", "source": 344, "speaker": "旁白", "text": "两个人对视。"},
		{"type": "line", "source": 345, "speaker": "旁白", "text": "那一瞬间，小凌突然觉得眼前这个女孩有一种说不出的熟悉感，像是在哪里见过。"},
		{"type": "asset_suppressed", "source": 346, "id": "mystery_girl_visual", "status": "神秘女孩人物素材槽保持为空；本并行版不显示人物。"},
		{"type": "line", "source": 347, "speaker": "旁白", "text": "又像是从来没有见过。"},
		{"type": "line", "source": 348, "speaker": "旁白", "text": "女孩伸手，轻轻摸了摸她的头发。"},
		{"type": "line", "source": 349, "speaker": "旁白", "text": "动作很轻。"},
		{"type": "line", "source": 350, "speaker": "旁白", "text": "却又熟悉得让小凌鼻子一酸。"},
		{"type": "action", "source": 351, "id": "hand_inspect_prepare", "status": "小凌抓住女孩的手；准备查看手上细节。"},
		{"type": "scene", "source": 352, "name": "剧情图-手"},
		{"type": "module_skip", "source": 353, "id": "HandInspect", "result": "continue"},
		{"type": "line", "source": 354, "speaker": "小凌", "text": "我们以前是不是见过？"},
		{"type": "line", "source": 355, "speaker": "女孩", "text": "（笑）可能吧"},
		{"type": "line", "source": 356, "speaker": "小凌", "text": "什么时候？"},
		{"type": "line", "source": 357, "speaker": "旁白", "text": "女孩没有回答。"},
		{"type": "line", "source": 358, "speaker": "旁白", "text": "不稳定的世界开始震动，小凌被晃得松开了女孩的手。"},
		{"type": "scene", "source": 359, "name": "剧情图-两个手松开的特写"},
		{"type": "module", "source": 360, "id": "BlinkInteraction", "scene": "res://modules/blink_interaction/blink_interaction.tscn", "completion_signal": "finished"},
		{"type": "line", "source": 362, "speaker": "小凌（很着急地）", "text": "什么时候？在哪儿见过？"},
		{"type": "line", "source": 363, "speaker": "旁白", "text": "女孩没有回答。"},
		{"type": "effect", "source": 364, "id": "world_shake", "status": "整个世界持续摇晃；动作状态失稳，小凌伸手但未抓住女孩。"},
		{"type": "line", "source": 364, "speaker": "旁白", "text": "整个世界在不断地摇晃震动，小凌和女孩被摇晃地站不住，小凌伸手想要抓住女孩，就要抓住的那一刻，"},
		{"type": "line", "source": 365, "speaker": "旁白", "text": "不稳定的世界关上了门……"},
		{"type": "blink_endpoint", "source": 366, "id": "blink_to_chapter3", "text": "（闭上眼睛再睁开，或按 F8，进入最终章。）"},
	]


static func required_scene_names() -> PackedStringArray:
	return PackedStringArray([
		"环境背景图0",
		"环境背景图1",
		"环境背景图2",
		"环境背景图3",
		"环境背景图4",
		"人物剧情图1",
		"环境背景图6",
		"溺水图cg",
		"环境背景图7",
		"主观内心背景图0",
		"剧情图-手",
		"剧情图-两个手松开的特写",
	])


static func required_module_hooks() -> PackedStringArray:
	return PackedStringArray([
		"ForestRun",
		"WaterfallInteraction",
		"TextInput",
		"LakeJump",
		"StarJar",
		"HandInspect",
		"BlinkInteraction",
	])
