class_name Chapter3TextRevealProfile
extends RefCounted

const REVEAL_SPEED_MULTIPLIER := 1.25
const BASE_SECONDS_PER_CHARACTER := 0.060
const BASE_MIN_SECONDS := 0.42
const BASE_MAX_SECONDS := 3.20
const BASE_SPEAKER_SECONDS_PER_CHARACTER := 0.055
const BASE_SPEAKER_MIN_SECONDS := 0.18
const BASE_SPEAKER_MAX_SECONDS := 0.48
const SECONDS_PER_CHARACTER := BASE_SECONDS_PER_CHARACTER / REVEAL_SPEED_MULTIPLIER
const MIN_SECONDS := BASE_MIN_SECONDS / REVEAL_SPEED_MULTIPLIER
const MAX_SECONDS := BASE_MAX_SECONDS / REVEAL_SPEED_MULTIPLIER
const SPEAKER_SECONDS_PER_CHARACTER := BASE_SPEAKER_SECONDS_PER_CHARACTER / REVEAL_SPEED_MULTIPLIER
const SPEAKER_MIN_SECONDS := BASE_SPEAKER_MIN_SECONDS / REVEAL_SPEED_MULTIPLIER
const SPEAKER_MAX_SECONDS := BASE_SPEAKER_MAX_SECONDS / REVEAL_SPEED_MULTIPLIER
const START_ALPHA := 0.24


static func duration_for(text: String) -> float:
    return clampf(float(text.length()) * SECONDS_PER_CHARACTER, MIN_SECONDS, MAX_SECONDS)


static func speaker_duration_for(text: String) -> float:
    return clampf(float(text.length()) * SPEAKER_SECONDS_PER_CHARACTER, SPEAKER_MIN_SECONDS, SPEAKER_MAX_SECONDS)


static func is_valid() -> bool:
    return (
        REVEAL_SPEED_MULTIPLIER > 0.0
        and SECONDS_PER_CHARACTER > 0.0
        and MAX_SECONDS > MIN_SECONDS
        and SPEAKER_MAX_SECONDS > SPEAKER_MIN_SECONDS
        and START_ALPHA > 0.0
        and START_ALPHA < 1.0
    )
